# -*- coding: utf-8 -*-
"""Hybrid Deepfake Tweet detection using stylometry and explainable AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOQxl0gRx17-PDjU0MR0S118C7B8x5me

**Step 1: Install Required Packages**
"""

!pip install transformers
!pip install xgboost
!pip install shap
!pip install lime
!pip install nltk==3.8.1
!pip install scikit-learn

import nltk
print(nltk.__version__)

"""# **Step 2: Import Libraries**"""

import pandas as pd
import numpy as np
import shap
import lime
import nltk
import xgboost as xgb

from transformers import RobertaTokenizer, RobertaModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
nltk.download("punkt")


import nltk
nltk.download("punkt")

"""# **step 3: Load Your Dataset (CSV)**"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

data_path = '/content/AI_Human.csv'

import pandas as pd

df = pd.read_csv(data_path, on_bad_lines='skip', engine='python')
#df = pd.read_json("/content/BERT-Defense_test_balanced_200.jsonl",lines=True)  # Replace with your actual file path
df = df[['text', 'generated']]
df.dropna(inplace=True)


# Encode labels: 0 = human, 1 = machine
le = LabelEncoder()
df['label'] = le.fit_transform(df['generated'])

"""# **Step 4: Stylometric Feature Extraction**"""

from nltk import word_tokenize, sent_tokenize

def extract_stylometric_features(text):
    words = word_tokenize(text)
    sentences = sent_tokenize(text)
    avg_word_len = np.mean([len(w) for w in words]) if words else 0
    avg_sent_len = np.mean([len(s.split()) for s in sentences]) if sentences else 0
    type_token_ratio = len(set(words)) / len(words) if words else 0
    punctuation_count = sum([1 for c in text if c in ".,;!?"])
    upper_case_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0

    return [avg_word_len, avg_sent_len, type_token_ratio, punctuation_count, upper_case_ratio]

stylometric_features = df['text'].apply(extract_stylometric_features)
stylometric_features = np.array(stylometric_features.tolist())

def generate_stylometric_explanation(text, features, mode='detailed'):
    avg_word_len, avg_sent_len, ttr, punct_count, upper_ratio = features

    import nltk
    from nltk.corpus import stopwords
    from nltk.tokenize import word_tokenize
    nltk.download('punkt')
    nltk.download('stopwords')

    words = word_tokenize(text)
    stopword_count = sum(1 for word in words if word.lower() in stopwords.words('english'))
    total_words = len(words)
    stopword_ratio = stopword_count / total_words if total_words > 0 else 0

    # Human-readable phrases instead of numeric ratios
    def describe_feature():
        explanation = "Based on stylometric analysis, the text "

        # Word Length
        if avg_word_len < 4:
            explanation += f"uses relatively short words, averaging {avg_word_len:.1f} characters, which often reflects a templated or machine-generated style. "
        else:
            explanation += f"contains moderately long words, averaging {avg_word_len:.1f} characters, indicating a more nuanced, human-like vocabulary. "

        # Sentence Length
        if avg_sent_len < 10:
            explanation += f"The sentences are quite short, averaging around {avg_sent_len:.1f} words per sentence, which may suggest automated phrasing or a lack of narrative depth. "
        else:
            explanation += f"Sentence structures are more elaborate, averaging {avg_sent_len:.1f} words, suggesting a natural, expressive writing pattern. "

        # TTR
        if ttr < 0.4:
            explanation += f"The lexical diversity is limited (low type-token ratio), showing frequent repetition of words, a trait often seen in AI-generated text. "
        else:
            explanation += f"The vocabulary is diverse, suggesting creative expression consistent with human authorship. "

        # Punctuation
        if punct_count < 2:
            explanation += f"Punctuation is sparse, giving the text a flat or robotic tone. "
        else:
            explanation += f"Punctuation is used appropriately, enhancing clarity and structure. "

        # Uppercase Ratio
        if upper_ratio > 0.3:
            explanation += f"There is an unusually high use of uppercase characters, which may indicate emphasis artifacts often found in automated or copied text. "
        else:
            explanation += f"Capitalization is balanced, aligning with typical human-written language. "

        # Stopword Ratio
        if stopword_ratio < 0.3:
            explanation += f"The text contains fewer stopwords, which can make it seem overly concise or abrupt. "
        else:
            explanation += f"The presence of common stopwords contributes to the natural flow of the sentences. "

        return explanation.strip()

    if mode == 'summary':
        return "✍️ **Stylometric Summary**:\n\n" + describe_feature()
    else:
        return "📊 **Stylometric Explanation Report**:\n\n" + describe_feature()

"""# **Step 5: Get RoBERTa Embeddings**"""

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaModel.from_pretrained('roberta-base')

def get_roberta_embeddings(text_list):
    model.eval()
    embeddings = []
    with torch.no_grad():
        for text in text_list:
            inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
            outputs = model(**inputs)
            cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()
            embeddings.append(cls_embedding)
    return np.array(embeddings)

roberta_embeddings = get_roberta_embeddings(df['text'].tolist())

"""# **Step 6: Combine Features**

"""

X = np.concatenate([roberta_embeddings, stylometric_features], axis=1)
y = df['label'].values

"""# **Step 7: Train-Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

print("✅ Saved train.csv and test.csv with shapes:")
print("Train:", X_train.shape)
print("Test :", X_test.shape)

"""# **Step 8: Train XGBoost Classifier**"""

xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)

"""# **Step 9: Evaluate Model**"""

y_pred = xgb_model.predict(X_test)
print("Classification Report:\n", classification_report(y_test, y_pred))

"""# **Step 10: SHAP Explainability**"""

explainer = shap.Explainer(xgb_model, X_train)
shap_values = explainer(X_test[:5])

shap.plots.bar(shap_values[0])

"""# **Step 11: LIME Explainability**"""

from lime.lime_tabular import LimeTabularExplainer

lime_explainer = LimeTabularExplainer(X_train, feature_names=[f'F{i}' for i in range(X.shape[1])],
                                      class_names=['Human', 'Machine'], discretize_continuous=True)

i = 0  # Example index
exp = lime_explainer.explain_instance(X_test[i], xgb_model.predict_proba, num_features=10)
exp.show_in_notebook()

"""# **Step 12: Natural Language Explanation Function**"""

def generate_natural_explanation(text, prediction, shap_values, stylometry_feats):
    label = "MACHINE" if prediction == 1 else "HUMAN"
    reasons = []
    if stylometry_feats[2] < 0.4:
        reasons.append("low lexical diversity (type-token ratio)")
    if stylometry_feats[0] < 3.5:
        reasons.append("short average word length")
    if stylometry_feats[4] < 0.05:
        reasons.append("few uppercase letters (robotic tone)")
    if shap_values.values.sum() > 0.5:
        reasons.append("semantic features strongly suggest AI pattern")

    return f"📥 Input Tweet: \"{text}\"\n\n🧠 Predicted Class: **{label}**\n🧠 Reason: " + ", ".join(reasons)

"""# **Heatmap Function**"""

def plot_shap_heatmap(shap_values_array, top_n=10):
    top_indices = np.argsort(np.abs(shap_values_array))[-top_n:][::-1]
    top_shap_values = shap_values_array[top_indices]
    feature_names = [f"Feature {i}" for i in top_indices]

    plt.figure(figsize=(10, 1))
    sns.heatmap(
        [top_shap_values],
        annot=True,
        fmt=".3f",
        cmap="coolwarm",
        xticklabels=feature_names,
        yticklabels=["SHAP"],
        cbar=True
    )
    plt.title("Top SHAP Feature Contributions")
    plt.tight_layout()
    plt.show()

"""# **Step 13: Example Final Output with Explanation**"""

def get_roberta_embeddings_batch(text_list):
    model.eval()
    with torch.no_grad():
        inputs = tokenizer(text_list, return_tensors="pt", padding=True, truncation=True, max_length=128)
        outputs = model(**inputs)
        cls_embeddings = outputs.last_hidden_state[:, 0, :].cpu().numpy()
    return cls_embeddings

import matplotlib.pyplot as plt
import shap
from lime.lime_tabular import LimeTabularExplainer
import numpy as np

def predict_and_explain_tweet():
    tweet = input("Enter a tweet: ")

    # --- Feature Extraction ---
    stylometric = extract_stylometric_features(tweet)
    roberta_embed = get_roberta_embeddings_batch([tweet])[0]
    sample_input = np.concatenate([roberta_embed, stylometric])

    # --- Prediction ---
    pred_probs = xgb_model.predict_proba([sample_input])[0]
    pred_class = np.argmax(pred_probs)
    confidence = round(pred_probs[pred_class] * 100, 2)

    # --- SHAP Explanation ---
    shap_values = explainer(np.array([sample_input]))
    shap_contributions = shap_values[0]
    shap_values_array = shap_contributions.values

    # --- LIME Explanation ---
    lime_exp = lime_explainer.explain_instance(
        sample_input,
        xgb_model.predict_proba,
        num_features=5
    )

    lime_explanation = lime_exp.as_list()

    # --- Natural Language SHAP Explanation ---
    explanation = generate_natural_explanation(tweet, pred_class, shap_contributions, stylometric)

    # --- Stylometric Explanation ---
    stylometric_report = generate_stylometric_explanation(tweet, stylometric)

    # --- Output ---
    print("\n📥 Input Tweet:", tweet)
    print(f"\n🧠 Predicted Class: {'HUMAN' if pred_class == 0 else 'MACHINE'}")
    print(f"📊 Model Confidence: {confidence}%")

    # --- SHAP Text Explanation ---
    print("\n🔎 SHAP Explanation (Top Features):")
    top_shap = sorted(enumerate(shap_values_array), key=lambda x: abs(x[1]), reverse=True)[:5]
    for i, val in top_shap:
        print(f"  • Feature {i}: SHAP value = {val:.4f}")

    # --- SHAP Bar Plot ---
    print("\n📊 SHAP Feature Importance Plot:")
    shap.plots.bar(shap_values[0])
    plt.show()

    # --- LIME Text Explanation ---
    print("\n🔎 LIME Explanation:")
    for feat, val in lime_explanation:
        print(f"  • {feat}: {val:.4f}")

    # --- LIME Plot ---
    print("\n📊 LIME Plot:")
    lime_exp.show_in_notebook(show_table=True, show_all=False)

    print("\n📚 Combined Explanation:")
    print(explanation)

    print("\n✍️ Stylometric Explanation:")
    print(stylometric_report)

# Call the function
predict_and_explain_tweet()